-- return {
--   "saghen/blink.cmp",
--   dependencies = {
--     "rafamadriz/friendly-snippets",
--     {
--       "L3MON4D3/LuaSnip",
--       version = "v2.*",
--       build = "make install_jsregexp",
--     },
--   },
--
--   version = '1.*',
--   opts = {
--     keymap = {
--       preset = 'default',
--       ["<C-k>"] = { "select_prev", "fallback" },
--       ["<C-j>"] = { "select_next", "fallback" },
--     },
--
--     appearance = {
--       use_nvim_cmp_as_default = true,
--       nerd_font_variant = 'mono'
--     },
--
--     completion = { documentation = { auto_show = true } },
--
--     sources = {
--       default = { 'lsp', 'path', 'snippets', 'buffer' },
--       providers = {
--         lsp = {
--           name = "lsp",
--           enabled = true,
--           module = "blink.cmp.sources.lsp",
--           kind = "LSP",
--           score_offset = 990,
--         },
--         snippets = {
--           name = "snippets",
--           enabled = true,
--           module = "blink.cmp.sources.snippets",
--           score_offset = 1000,
--         },
--         luasnip = {
--           name = "luasnip",
--           enabled = true,
--           module = "blink.cmp.sources.luasnip",
--           score_offset = 1000,
--         },
--       },
--     },
--
--     fuzzy = { implementation = "prefer_rust_with_warning" }
--   },
--   opts_extend = { "sources.default" }
-- }
--
return {}
